# Use python, since we install and use aws cli during the build
language: python
python:
  - "3.6"

env:
  global:
    - AWS_REGION=us-east-2
    - AWS_ACCESS_KEY_ID=AKIAIPJXMNOEV65OMURA
    # Encrypted AWS_SECRET_ACCESS_KEY
    - secure: "KGqbZdK65Z/fwuM8XkIO7awap+hastKvpAXJPe1FvwwZ9QGK+t9ZDljyIN8oSZdEPH4te7opo5D5LxNVVbFuTfnQ4P3Mikl7aOoGQi39wx5XmBueeQB+r/fl1GjkOoRcHyLmRRbeP4Ux/VDG2cCNUsS9q/s6kqsf8k0RmcpDMn0tBef/CixdnTfoQxO8QOgDCoBt+ErBamgt/HFWM89bw4uaehXwoevgArVkaiFyyJv3xBpKRAWKYPuwxCc9iadbb13SiPbs5qx0lQulrYLzf3qkQKBBJRGAPysC7uITW10TY/KjxmHA4S6+Z67P5GK5khZ55xsC86gz0fgWHFCdflbu46kS2bkAozEf9HnU3cDV3sHMgPyIOaAgGwmYjcDjwE+oxa54sTfzEwZ1yAKY3twwDiKue/4hdaHVknoWUJdjL7s5fOS3XXl3g8pHsRvzAx9XO8ZAOv7n2Pf0UvGbgklbTgDQO+Vvi7jDJb1yXGT6o9YFTpazpj5R3kU1Nf3V28zNQ8/OGqKssKghgT/9Cm1DqZIWWiPHmbkF6Q7e/HBSgTLaRd/PI//C/pSlc25TO/vQ+hBoqdxZ/1FCDDiCpLCXxd1b33ea3HUKBtmKKtSWDYGo6VVI8X+PCx7DvzpWIX85xgLhvloTUeNUL4ly/dcVhuEDiq5eWGHdcw20NmY="
    - S3_BUCKET="docksal-aws-templates"
    - UPLOAD_DIR="sandbox-server"
    - LOCAL_DIR="build"

  matrix:
    - TEMPLATE_TYPE=basic
    - TEMPLATE_TYPE=advanced

install:
  - pip install awscli --upgrade

script:
  - cd aws-cloudformation && ./scripts/bash2yaml startup-${TEMPLATE_TYPE}.sh tpl-${TEMPLATE_TYPE}.yaml
  - mkdir -p ${LOCAL_DIR} && mv -f template.yaml ${LOCAL_DIR}/${TEMPLATE_TYPE}.yaml
  - tmp=$(mktemp) && cp ${LOCAL_DIR}/${TEMPLATE_TYPE}.yaml ${tmp}
  - aws s3 cp ${tmp} s3://${S3_BUCKET}/$(basename ${tmp}) --acl public-read
  - res=$(aws cloudformation validate-template --region ${AWS_REGION} --template-url https://${S3_BUCKET}.s3.amazonaws.com/$(basename ${tmp}) || echo "error")
  - aws s3 rm s3://${S3_BUCKET}/$(basename ${tmp})
  - if [ "${res}" == "error" ]; then exit 1; fi
  - ${TRAVIS_BUILD_DIR}/scripts/upload-to-s3.sh
