#!/bin/bash
#
# This script create aws stack using template file template.json
#

[ "$1" != "" ] && { stack_name=$1; } || { echo "Usage: $0 stack-name"; exit; }

aws cloudformation create-stack --stack-name $stack_name --template-body file://template.json >/dev/null && echo "Creation stack $stack_name is in progress..." || exit 1
aws cloudformation wait stack-create-complete --stack-name $stack_name && echo "Stack $stack_name created!" || { echo "Timeout creation stack $stack_name"; exit 1; }
aws cloudformation describe-stacks --stack-name $stack_name
