#!/bin/bash
#
# This script add generated ssh key into all aws cloud regions
#

[ $1 != "" ] && { keyname=$1; } || { echo "Usage: $0 keyname"; exit; }

[ ! -f .ssh/$keyname.pub ] && { echo "Keyfile .ssh/$keyname.pub not found"; exit 1; }
AWS_REGION=$(aws ec2 describe-regions --output text | awk '{print $3}' | xargs)

for region in $AWS_REGION
do
    aws ec2 import-key-pair --key-name $keyname --public-key-material file://.ssh/$keyname.pub --region $region
done
