imports:
- path: Docksal.jinja
- path: startup.sh

resources:
- name: Docksal
  type: Docksal.jinja
  properties:
    zone: us-east4-c
    machineType: n1-standard-2
    dataDiskSizeGb: 100
    metadata-from-file:
      startup-script: startup.sh

outputs:
- name: ip
  value: $(ref.Docksal.vmExternalIP)
