#!/bin/bash
#
# This script converts bash scripts to yaml format and create ready to deploy template.yaml
#

[[ "$1" == "" ]] && { echo "Usage: $0 script filename"; exit; }

template_file="template.tpl.yaml"

lines_num=`grep -n "^[[:space:]]*- - |" ${template_file} | cut -d':' -f 1`

:>template.yaml

prev_line_num=1

for line_num in ${lines_num}
do
	sed -n ${prev_line_num},${line_num}p ${template_file} >>template.yaml
	line=$(sed -n ${line_num}p ${template_file})
	prepend=$(printf %$(expr ${#line} - 1)s)
	sed "s/^/${prepend}/g" $1 >>template.yaml
	prev_line_num=$(expr ${line_num} + 1)
done

tail -n +${prev_line_num} ${template_file} >>template.yaml


