#!/bin/bash
#
# This script converts bash scripts to json format
# Script output must be inserted in template.json in section UserData
#

[[ "$1" == "" ]] && { echo "Usage: $0 script filename"; exit; }

echo "        "
sed 's/"/\\"/g' $1 | awk '{print "        \""$0"\\n\","}'
echo "        \"\n\""