#!/bin/bash

AWS_REGION=$(aws ec2 describe-regions --output text | awk '{print $3}' | xargs)

echo '    "Region2AMI" : {'
for region in ${AWS_REGION}
do
    ami=`aws ec2 describe-images --region ${region} --owners 099720109477 --filters --output json 'Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-????????' 'Name=state,Values=available' | jq -r '.Images | sort_by(.CreationDate) | last(.[]).ImageId'`
    echo '      "'${region}'" : { "AMI" : "'${ami}'" },'
done
echo '    }'
