#!/bin/bash
#
# This script add generated ssh key into all aws cloud regions
#

[[ $1 == "" ]] && { echo "Usage: $0 keyname"; exit; }

[[ ! -f $HOME/.ssh/${1}.pub ]] && { echo "Public key file not found in $HOME/.ssh/${1}.pub"; exit 1 }

AWS_REGION=$(aws ec2 describe-regions --output text | awk '{print $3}' | xargs)

for region in ${AWS_REGION}
do
	aws ec2 import-key-pair --key-name ${1} --public-key-material file://$HOME/.ssh/${1}.pub --region ${region}
done
