#!/bin/bash
#
# This script deletes an SSH key in all aws regions
#

[[ $1 == "" ]] && { echo "Usage: $0 keyname"; exit; }

AWS_REGION=$(aws ec2 describe-regions --output text | awk '{print $3}' | xargs)

for region in ${AWS_REGION}
do
	aws ec2 delete-key-pair --key-name ${1} --region ${region}
done
